spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
  main:
    log-startup-info: false
